version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  backend:
    image: node:20-alpine
    ports: 
      - "4000:4000"
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: ["/bin/sh", "-c", "npm install && npm start"]
    links:
      - "db:db"
    depends_on:
      - db

volumes:
  db:
    driver: local
